//
//  ChapterViewController.swift
//  EdgeViewer
//
//  Created by bmmkac on 4/30/18.
//  Copyright © 2018 NoName. All rights reserved.
//

import Cocoa

class ChapterViewController: NSSplitViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do view setup here.
        // overriding layout generated by AutoLayout
        if let view = splitViewItems[0].viewController.view.superview {
            for constraint in view.constraints {
                if constraint.firstAttribute == .width && constraint.relation == .greaterThanOrEqual {
                    constraint.constant = 150
                }
            }
        }
    }
}
