//
//  LibraryViewController.swift
//  EdgeViewer
//
//  Created by YunSang Lee on 2018. 4. 14..
//  Copyright © 2018년 NoName. All rights reserved.
//

import Cocoa

class LibraryViewController: NSSplitViewController {
    
    var listViewController: LibraryListViewController? = nil
    var shelfViewController: ShelfViewController? = nil

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do view setup here.
        
        for item in splitViewItems {
            switch item.viewController {
                case let viewController as ShelfViewController:
                    shelfViewController = viewController
                case let viewController as LibraryListViewController:
                    listViewController = viewController
                default:
                    print("error")
            }
        }
        
        // overriding layout generated by AutoLayout
        if let view = listViewController!.view.superview {
            for constraint in view.constraints {
                if constraint.firstAttribute == .width && constraint.relation == .greaterThanOrEqual {
                    constraint.constant = 150
                }
            }
        }
    }
}
